// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.API.Data;

#nullable disable

namespace NZWalks.API.Migrations
{
    [DbContext(typeof(NZWalksDBContext))]
    [Migration("20240116111828_Seeding Data For Difficulties and Regions")]
    partial class SeedingDataForDifficultiesandRegions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c7b6bfa2-7cf3-4a06-8c5a-582dc531e6c8"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("7887f7b9-5edb-46d1-8cdc-a26e5df926d5"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("c274310d-5adb-44f2-a241-5b4a11a41e57"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ff729a6-35c5-4524-aa19-8194ebba88c6"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcSbtmRCui6cHdhj9GjDOoUyIWIQ6Uf-K_AXud-wgl6frpAkB5XYBNClHhNjyPfKEve4lozjoXS_2sCPbu3FmOw1Iq9D5iKF5pahkOOaYA"
                        },
                        new
                        {
                            Id = new Guid("bea81efc-fdf4-4b29-8ba5-1c32ea479b3b"),
                            Code = "NTL",
                            Name = "Northland",
                            RegionImageUrl = "https://lp-cms-production.imgix.net/2019-06/14e0f74f559b51878ae048fbd6b81be6ef9272af969a7e3d1b1d5482920cf9b8.jpg"
                        },
                        new
                        {
                            Id = new Guid("57c1f6c8-df1f-47ff-a6e1-7386b00d524e"),
                            Code = "BOP",
                            Name = "Bay Of Plenty",
                            RegionImageUrl = "https://www.newzealand.com/assets/Tourism-NZ/Bay-of-Plenty/6d1047c26a/img-1536927287-1206-10060-p-7CD33CA5-0906-4B8F-DC8DDBFCCE92BB46-2544003__aWxvdmVrZWxseQo_CropResizeWzE5MDAsMTAwMCw3NSwicG5nIl0.png"
                        },
                        new
                        {
                            Id = new Guid("54c87543-f499-448f-9db7-c5ad06b5937b"),
                            Code = "WGN",
                            Name = "Wellington",
                            RegionImageUrl = "https://wellington.govt.nz/-/media/wellington-city/about-wellington/profile/images/86568_1763_rt.jpg"
                        },
                        new
                        {
                            Id = new Guid("11c7a514-d8bf-402c-a87a-8161b3903467"),
                            Code = "NSN",
                            Name = "Nelson",
                            RegionImageUrl = "https://www.eatworktravel.com/wp-content/uploads/2017/04/Nelson-New-Zealand-4711.jpg"
                        },
                        new
                        {
                            Id = new Guid("0489db1b-80ae-4324-9525-84b32b8408f6"),
                            Code = "STL",
                            Name = "Southland",
                            RegionImageUrl = "https://assets.simpleviewinc.com/simpleview/image/upload/c_limit,h_1200,q_75,w_1200/v1/clients/southlandnz/Riverton_Southland_New_Zealand_Credit_Great_South_3__6fa0c09a-a1e3-414a-bf34-be25daa667b9.jpg"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
